name: Publish Packages to npm

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      hooks: ${{ steps.filter.outputs.hooks }}
      components: ${{ steps.filter.outputs.components }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect Changed Packages
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            hooks:
              - 'packages/hooks/**'
            components:
              - 'packages/components/**'

  install-dependencies:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.hooks == 'true' || needs.changes.outputs.components == 'true'
    outputs:
      cache-hit: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install root dependencies
        run: npm ci

  publish-hooks:
    needs: [changes, install-dependencies]
    if: needs.changes.outputs.hooks == 'true'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/hooks

    steps:
      - uses: actions/checkout@v4

      - name: Build hooks
        run: npm run build

      - name: Publish hooks
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-components:
    needs: [changes, install-dependencies]
    if: needs.changes.outputs.components == 'true'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/components

    steps:
      - uses: actions/checkout@v4

      - name: Build components
        run: npm run build

      - name: Publish components
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
